add-database
TyushaMG/java-filmorate pull request #3
Opened 2023-03-20 12:41 UTC by TyushaMG

2023-03-20 23:17 UTC, SnikerZi requested changes
Привет, Маргарита, ты написала неплохую работу. У меня есть пара предолжений по улучшению твоего кода.
Также у тебя отстутствует скриншот\ссылка на схему базы данных и скрипт создания базы данных.
ValidationException, стоит сделать поле message final.
Желаю успехов в доработке твоей программы. Если у тебя возникнут вопросы по ревью, то ты можешь написать мне в пачке.

2023-03-20 23:17 UTC, SnikerZi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Collection<Film> collect = filmStorage.getPopular(count);
Стоит сразу возвращать значение, без инициализации дополнительной переменной

2023-03-20 23:17 UTC, SnikerZi commented on src/test/java/ru/yandex/practicum/filmorate/ValidationTests.java
> +   /* @Test
закоментированных строк кода быть не должно, если тесты не проходят, то их необходимо переписать, если же тесты не нужны тут вообще, то их стоит удалить в принципе.

2023-03-21 08:26 UTC, TyushaMG commented
Спасибо за ревью! Добавила скрин, схему и поправила все комментарии

2023-03-24 08:30 UTC, merged